name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # step 1: 소스코드 복사
      - name: 코드 가져오기
        uses: actions/checkout@v3

      # step 2: java 환경 구성
      - name: JDL 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # step 3: maven 빌드
      - name: Maven 빌드
        run: mvn clean package

      # step 4: 결과 확인
      - name: 빌드 결과 확인
        run: ls -la target/

