name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: JDL 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Maven 빌드
        run: mvn clean package

      - name: 빌드 아티팩트 업로드
      - uses: actions/upload-artifact@v3
        with:
          name: jar-artifact
          path: target/*.jar